#!/bin/bash
# This script switches between HDMI output and
# headphones output on the raspberry pi
function set {
    if [[ $1 == "headphones" ]]
    then
        sudo amixer cset numid=3 1
    elif [[ $1 == "hdmi" ]]
    then
        sudo amixer cset numid=3 2
    elif [[ $1 == "auto" ]]
    then
        sudo amixer cset numid=3 0
    else
        echo "This option does not exist"
    fi
}
if [[ "$#" == "1" ]]
then
    set $1
    exit 0
fi
CURRENT_MODE=`sudo amixer cget numid=3 | grep ": values" | sed -e "s/.*: values=\(1\).*/\1/g"`
if [[ "$CURRENT_MODE" == "1" ]]
then
    set hdmi
elif [[ "$CURRENT_MODE" == "2" ]]
then
    set headphones
else
    set headphones
fi
